export const COMPONENT_GROUPS = [
  { title: "Forms", items: ["button", "input", "textarea", "select", "checkbox", "checkbox-group", "switch", "radio", "radio-group", "slider", "label", "field", "form", "fieldset", "input-group", "autocomplete", "combobox", "number-field", "otp-field", "calendar", "date-picker"] },
  { title: "Display", items: ["card", "badge", "avatar", "tabs", "segmented-control", "dialog", "alert-dialog", "alert", "empty", "toggle", "meter", "accordion", "collapsible", "breadcrumb", "kbd", "group", "toggle-group", "pagination", "frame", "scroll-area", "sidebar", "navigation-menu", "menubar", "toolbar", "sheet", "drawer", "menu", "context-menu", "command", "filterable-menu", "dropdown-menu", "popover", "preview-card", "tooltip", "toast", "spinner", "separator", "progress", "skeleton"] },
  { title: "Data", items: ["table", "data-table", "kpi-card", "chart-line", "chart-area", "chart-bar", "chart-pie", "chart-sparkline", "chart-funnel", "chart-heatmap", "chart-radial", "chart-stacked-area", "chart-grouped-bar", "chart-normalized-bar", "chart-composed", "chart-radar", "chart-scatter", "chart-bubble", "chart-treemap", "chart-gauge", "chart-progress", "chart-waterfall", "chart-lollipop", "chart-dumbbell", "chart-bullet", "chart-slope", "chart-stream", "chart-calendar", "chart-sankey", "chart-chord", "chart-boxplot", "chart-violin", "chart-density", "chart-histogram", "chart-dot", "chart-pareto", "chart-control", "chart-multi-axis", "chart-step", "chart-range", "chart-band", "chart-rose", "chart-polar", "chart-timeline", "chart-interval", "chart-candlestick", "chart-funnel-horizontal", "chart-metric-grid", "chart-cohort", "chart-retention", "chart-geo", "chart-live", "chart-small-multiples", "chart-stacked-bar"] },
  { title: "Dashboard", items: ["dashboard-overview", "dashboard-activity", "dashboard-alerts", "dashboard-comparison", "dashboard-timeline", "dashboard-command-center"] },
  { title: "Blocks", items: ["filter-bar"] },
] as const

export const COMPONENT_NAMES = COMPONENT_GROUPS.flatMap((group) => group.items)

export const HOOKS = [
  { name: "use-copy-to-clipboard", title: "useCopyToClipboard", description: "Copy text with a temporary copied state and optional callback." },
  { name: "use-media-query", title: "useMediaQuery", description: "Reactively match breakpoints, pointers, or any CSS media query." },
] as const

export const COMPONENT_DESCRIPTIONS: Record<string, string> = {
  button: "Triggers an action with COSS-style variants, sizes, icons, and loading state.",
  input: "Single-line text entry with focus, validation, disabled, and size states.",
  textarea: "Multi-line text entry for longer messages and notes.",
  select: "A keyboard-friendly listbox for choosing one option from a menu.",
  checkbox: "A binary control for selecting one or more independent options.",
  "checkbox-group": "A semantic group of related checkbox controls.",
  switch: "A compact control for toggling a setting on or off.",
  "radio-group": "A mutually exclusive set of options with a single selected value.",
  radio: "A single selectable radio control.",
  slider: "A draggable range control for selecting a numeric value.",
  label: "An accessible label for a form control.",
  field: "A composed label, control, description, and validation message pattern.",
  form: "A semantic layout primitive for submitting related controls.",
  fieldset: "A labeled group of related form controls.",
  "input-group": "A composed input with leading or trailing addons.",
  autocomplete: "An input that suggests filtered options as you type.",
  combobox: "An input and listbox for choosing from known options.",
  "number-field": "A numeric input with accessible increment and decrement controls.",
  "otp-field": "A segmented numeric input for one-time verification codes.",
  calendar: "A month grid for choosing and reviewing dates.",
  "date-picker": "A popover date selection flow built on Calendar.",
  card: "A layered surface for grouping related content and actions.",
  badge: "A compact status label for categorization and state.",
  avatar: "A visual identity marker with image and fallback content.",
  tabs: "A horizontal navigation pattern for switching between related panels.",
  "segmented-control": "A compact set of related choices for navigation, filtering, or view selection.",
  dialog: "A modal surface for focused tasks without leaving the current page.",
  "alert-dialog": "A blocking confirmation surface for consequential actions.",
  alert: "A semantic callout for important status or feedback.",
  empty: "A calm placeholder for views with no content yet.",
  toggle: "A compact button that exposes an on or off pressed state.",
  meter: "A semantic gauge for a scalar value within a known range.",
  accordion: "A stack of collapsible sections for progressively disclosed content.",
  collapsible: "A single content section that can be expanded or tucked away.",
  breadcrumb: "Hierarchical navigation that shows the current location.",
  kbd: "A compact keyboard-key label for shortcuts and command hints.",
  group: "A semantic grouping primitive for related controls.",
  "toggle-group": "A coordinated set of pressed controls for one or more choices.",
  pagination: "Navigation controls for moving through a collection of pages.",
  frame: "A bordered surface for presenting content with an optional header.",
  "scroll-area": "A constrained region with predictable overflow scrolling.",
  menu: "A discoverable list of actions anchored to a trigger.",
  sidebar: "A persistent navigation surface for application sections.",
  sheet: "A modal side surface for focused navigation or editing tasks.",
  drawer: "A side surface for navigation or focused editing tasks.",
  "context-menu": "A pointer-anchored menu of actions for the current context.",
  toast: "A transient notification for completed actions and important updates.",
  "preview-card": "An anchored rich preview for a linked resource.",
  "navigation-menu": "A semantic primary navigation surface for related routes.",
  toolbar: "A semantic row of grouped actions and controls.",
  menubar: "A horizontal menu of top-level application actions.",
  "filterable-menu": "A searchable list of actions for dense command surfaces.",
  command: "A keyboard-first searchable surface for application commands.",
  "dropdown-menu": "A contextual menu of actions anchored to a trigger.",
  popover: "A lightweight anchored surface for supplemental content or controls.",
  tooltip: "A brief contextual hint revealed on hover or focus.",
  spinner: "A compact loading indicator for async operations and pending states.",
  separator: "A visual divider for separating groups of related content.",
  progress: "A determinate progress indicator for work moving toward completion.",
  skeleton: "A quiet loading placeholder that preserves layout while content is arriving.",
  "data-table": "A sortable, paginated table for structured business data.",
  table: "A lightweight compositional table for ordinary tabular content.",
  "kpi-card": "A compact metric surface with value, delta, and optional trend.",
  "chart-line": "A time-series line chart for tracking continuous change.",
  "chart-area": "An area chart for comparing volume and cumulative movement.",
  "chart-bar": "A bar chart for comparing discrete categories.",
  "chart-pie": "A pie or donut chart for showing part-to-whole relationships.",
  "chart-sparkline": "A compact trend visualization for use inside metric surfaces.",
  "chart-funnel": "A staged conversion chart for visualizing drop-off across a journey.",
  "chart-heatmap": "A compact grid for comparing intensity across days, cohorts, or segments.",
  "chart-radial": "A radial progress chart for comparing attainment against a shared target.",
  "chart-stacked-bar": "A stacked bar chart composition for analytics dashboards.",
  "chart-small-multiples": "A small multiples chart composition for analytics dashboards.",
  "chart-live": "A live chart composition for analytics dashboards.",
  "chart-geo": "A geo chart composition for analytics dashboards.",
  "chart-retention": "A retention chart composition for analytics dashboards.",
  "chart-cohort": "A cohort chart composition for analytics dashboards.",
  "chart-metric-grid": "A metric grid chart composition for analytics dashboards.",
  "chart-funnel-horizontal": "A funnel horizontal chart composition for analytics dashboards.",
  "chart-candlestick": "A candlestick chart composition for analytics dashboards.",
  "chart-interval": "A interval chart composition for analytics dashboards.",
  "chart-timeline": "A timeline chart composition for analytics dashboards.",
  "chart-polar": "A polar chart composition for analytics dashboards.",
  "chart-rose": "A rose chart composition for analytics dashboards.",
  "chart-band": "A band chart composition for analytics dashboards.",
  "chart-range": "A range chart composition for analytics dashboards.",
  "chart-step": "A step chart composition for analytics dashboards.",
  "chart-multi-axis": "A multi axis chart composition for analytics dashboards.",
  "chart-control": "A control chart composition for analytics dashboards.",
  "chart-pareto": "A pareto chart composition for analytics dashboards.",
  "chart-dot": "A dot chart composition for analytics dashboards.",
  "chart-histogram": "A histogram chart composition for analytics dashboards.",
  "chart-density": "A density chart composition for analytics dashboards.",
  "chart-violin": "A violin chart composition for analytics dashboards.",
  "chart-boxplot": "A boxplot chart composition for analytics dashboards.",
  "chart-chord": "A chord chart composition for analytics dashboards.",
  "chart-sankey": "A sankey chart composition for analytics dashboards.",
  "chart-calendar": "A calendar chart composition for analytics dashboards.",
  "chart-stream": "A stream chart composition for analytics dashboards.",
  "chart-slope": "A slope chart composition for analytics dashboards.",
  "chart-bullet": "A bullet chart composition for analytics dashboards.",
  "chart-dumbbell": "A dumbbell chart composition for analytics dashboards.",
  "chart-lollipop": "A lollipop chart composition for analytics dashboards.",
  "chart-waterfall": "A waterfall chart composition for analytics dashboards.",
  "chart-progress": "A progress chart composition for analytics dashboards.",
  "chart-gauge": "A gauge chart composition for analytics dashboards.",
  "chart-treemap": "A treemap chart composition for analytics dashboards.",
  "chart-bubble": "A bubble chart composition for analytics dashboards.",
  "chart-scatter": "A scatter chart composition for analytics dashboards.",
  "chart-radar": "A radar chart composition for analytics dashboards.",
  "chart-composed": "A composed chart composition for analytics dashboards.",
  "chart-normalized-bar": "A normalized bar chart composition for analytics dashboards.",
  "chart-grouped-bar": "A grouped bar chart composition for analytics dashboards.",
  "chart-stacked-area": "A stacked area chart composition for analytics dashboards.",
  "dashboard-overview": "A composed analytics surface combining KPIs, trends, mix, funnel, and retention charts.",
  "dashboard-command-center": "Reusable dashboard command center block for analytics products.",
  "dashboard-timeline": "Reusable dashboard timeline block for analytics products.",
  "dashboard-comparison": "Reusable dashboard comparison block for analytics products.",
  "dashboard-alerts": "Reusable dashboard alerts block for analytics products.",
  "dashboard-activity": "Reusable dashboard activity block for analytics products.",
  "filter-bar": "A composed block for search, filters, reset, and result context.",
}
