/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CossProtoRouteImport } from './routes/coss-proto'
import { Route as StudioShellProtoRouteImport } from './routes/studio-shell-proto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CossProtoRoute = CossProtoRouteImport.update({
  id: '/coss-proto',
  path: '/coss-proto',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioShellProtoRoute = StudioShellProtoRouteImport.update({
  id: '/studio-shell-proto',
  path: '/studio-shell-proto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coss-proto': typeof CossProtoRoute
  '/studio-shell-proto': typeof StudioShellProtoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coss-proto': typeof CossProtoRoute
  '/studio-shell-proto': typeof StudioShellProtoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coss-proto': typeof CossProtoRoute
  '/studio-shell-proto': typeof StudioShellProtoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coss-proto' | '/studio-shell-proto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coss-proto' | '/studio-shell-proto'
  id: '__root__' | '/' | '/coss-proto' | '/studio-shell-proto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CossProtoRoute: typeof CossProtoRoute
  StudioShellProtoRoute: typeof StudioShellProtoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coss-proto': {
      id: '/coss-proto'
      path: '/coss-proto'
      fullPath: '/coss-proto'
      preLoaderRoute: typeof CossProtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-shell-proto': {
      id: '/studio-shell-proto'
      path: '/studio-shell-proto'
      fullPath: '/studio-shell-proto'
      preLoaderRoute: typeof StudioShellProtoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CossProtoRoute: CossProtoRoute,
  StudioShellProtoRoute: StudioShellProtoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
