import type { SemanticToken, System } from "./model.js";
import { knobVars, ramp } from "./knob-vars.js";

const fontStack = (families: string[]) => families.join(", ");

function declarations(pairs: Record<string, string>, indent = "  "): string {
  return Object.entries(pairs)
    .map(([k, v]) => `${indent}${k}: ${v};`)
    .join("\n");
}

function tokenBlock(sys: System, mode: "light" | "dark"): Record<string, string> {
  const m = sys[mode];
  return {
    ...ramp(sys.ramp, mode === "dark"),
    ...Object.fromEntries(
      Object.entries(m.semantic).map(([k, v]) => [`--${k}`, v as string]),
    ),
    "--font-sans": fontStack(sys.fonts.sans),
    ...(sys.fonts.serif ? { "--font-serif": fontStack(sys.fonts.serif) } : {}),
    "--font-mono": fontStack(sys.fonts.mono),
    "--radius": sys.radius,
    ...knobVars(sys.knobs),
  };
}

export function emitStylesheet(sys: System): string {
  const light = tokenBlock(sys, "light");
  const dark = tokenBlock(sys, "dark");
  const scope = `[data-raya="${sys.slug}"]`;
  const header = `/* Raya System "${sys.name}" (${sys.slug}) — generated by Export, do not edit by hand */`;

  const parts: string[] = [header];

  if (sys.isDefault) {
    parts.push(`:root {\n${declarations(light)}\n}`);
    parts.push(`.dark {\n${declarations(dark)}\n}`);
  }

  parts.push(`${scope} {\n${declarations(light)}\n}`);
  parts.push(`${scope}.dark {\n${declarations(dark)}\n}`);

  return parts.join("\n\n") + "\n";
}

export interface SystemConfig {
  slug: string;
  name: string;
  description: string;
  isDefault: boolean;
  fonts: System["fonts"];
  radius: string;
  ramp: { names: string; steps: number };
  knobs: System["knobs"];
  stylesheet: string;
}

export function emitConfig(sys: System): SystemConfig {
  return {
    slug: sys.slug,
    name: sys.name,
    description: sys.description,
    isDefault: Boolean(sys.isDefault),
    fonts: sys.fonts,
    radius: sys.radius,
    ramp: { names: "--raya-accent-1..12", steps: 12 },
    knobs: sys.knobs,
    stylesheet: `src/styles/raya/systems/${sys.slug}.css`,
  };
}
