import type { SemanticToken, System } from "./model.js";
import { defaultKnobs } from "./model.js";

const semantic = (
  pairs: Record<string, string>,
): Partial<Record<SemanticToken, string>> => pairs;

export const baseline: System = {
  slug: "baseline",
  name: "Baseline",
  description: "Raya's default look — quiet, rounded, blue-violet accent.",
  isDefault: true,
  fonts: {
    sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
    serif: ["Instrument Serif", "Georgia", "serif"],
    mono: ["JetBrains Mono", "ui-monospace", "monospace"],
  },
  radius: "0.625rem",
  ramp: { hue: 255, chroma: 0.14 },
  light: {
    semantic: semantic({
      background: "oklch(0.985 0.002 255)",
      foreground: "oklch(0.22 0.02 255)",
      card: "oklch(1 0 0)",
      "card-foreground": "oklch(0.22 0.02 255)",
      popover: "oklch(1 0 0)",
      "popover-foreground": "oklch(0.22 0.02 255)",
      primary: "var(--raya-accent-8)",
      "primary-foreground": "oklch(0.99 0.002 255)",
      secondary: "var(--raya-accent-2)",
      "secondary-foreground": "oklch(0.28 0.03 255)",
      muted: "var(--raya-accent-2)",
      "muted-foreground": "oklch(0.5 0.02 255)",
      accent: "var(--raya-accent-3)",
      "accent-foreground": "oklch(0.25 0.03 255)",
      destructive: "oklch(0.58 0.22 27)",
      border: "var(--raya-accent-4)",
      input: "var(--raya-accent-5)",
      ring: "var(--raya-accent-7)",
      "chart-1": "var(--raya-accent-7)",
      "chart-2": "var(--raya-accent-9)",
      "chart-3": "var(--raya-accent-5)",
      "chart-4": "var(--raya-accent-11)",
      "chart-5": "var(--raya-accent-3)",
      sidebar: "var(--raya-accent-2)",
      "sidebar-foreground": "oklch(0.24 0.02 255)",
      "sidebar-primary": "var(--raya-accent-8)",
      "sidebar-primary-foreground": "oklch(0.99 0.002 255)",
      "sidebar-accent": "var(--raya-accent-4)",
      "sidebar-accent-foreground": "oklch(0.26 0.03 255)",
      "sidebar-border": "var(--raya-accent-5)",
      "sidebar-ring": "var(--raya-accent-7)",
    }),
  },
  dark: {
    semantic: semantic({
      background: "oklch(0.17 0.02 255)",
      foreground: "oklch(0.94 0.005 255)",
      card: "oklch(0.21 0.025 255)",
      "card-foreground": "oklch(0.94 0.005 255)",
      popover: "oklch(0.21 0.025 255)",
      "popover-foreground": "oklch(0.94 0.005 255)",
      primary: "var(--raya-accent-7)",
      "primary-foreground": "oklch(0.15 0.02 255)",
      secondary: "var(--raya-accent-4)",
      "secondary-foreground": "oklch(0.92 0.01 255)",
      muted: "var(--raya-accent-3)",
      "muted-foreground": "oklch(0.68 0.02 255)",
      accent: "var(--raya-accent-4)",
      "accent-foreground": "oklch(0.93 0.01 255)",
      destructive: "oklch(0.62 0.2 25)",
      border: "var(--raya-accent-6)",
      input: "var(--raya-accent-5)",
      ring: "var(--raya-accent-6)",
      "chart-1": "var(--raya-accent-6)",
      "chart-2": "var(--raya-accent-8)",
      "chart-3": "var(--raya-accent-4)",
      "chart-4": "var(--raya-accent-10)",
      "chart-5": "var(--raya-accent-5)",
      sidebar: "oklch(0.19 0.02 255)",
      "sidebar-foreground": "oklch(0.93 0.005 255)",
      "sidebar-primary": "var(--raya-accent-7)",
      "sidebar-primary-foreground": "oklch(0.15 0.02 255)",
      "sidebar-accent": "var(--raya-accent-5)",
      "sidebar-accent-foreground": "oklch(0.92 0.01 255)",
      "sidebar-border": "var(--raya-accent-6)",
      "sidebar-ring": "var(--raya-accent-6)",
    }),
  },
  knobs: defaultKnobs,
};

export const terminal: System = {
  slug: "terminal",
  name: "Terminal",
  description: "Monospaced, square-cornered, phosphor green on near-black.",
  fonts: {
    sans: ["JetBrains Mono", "ui-monospace", "monospace"],
    mono: ["JetBrains Mono", "ui-monospace", "monospace"],
  },
  radius: "0rem",
  ramp: { hue: 150, chroma: 0.16 },
  light: {
    semantic: semantic({
      background: "oklch(0.97 0.005 150)",
      foreground: "oklch(0.18 0.01 150)",
      card: "oklch(0.99 0.003 150)",
      "card-foreground": "oklch(0.18 0.01 150)",
      popover: "oklch(0.99 0.003 150)",
      "popover-foreground": "oklch(0.18 0.01 150)",
      primary: "var(--raya-accent-8)",
      "primary-foreground": "oklch(0.98 0.003 150)",
      secondary: "var(--raya-accent-2)",
      "secondary-foreground": "oklch(0.25 0.02 150)",
      muted: "var(--raya-accent-2)",
      "muted-foreground": "oklch(0.45 0.03 150)",
      accent: "var(--raya-accent-3)",
      "accent-foreground": "oklch(0.22 0.02 150)",
      destructive: "oklch(0.55 0.22 29)",
      border: "var(--raya-accent-6)",
      input: "var(--raya-accent-6)",
      ring: "var(--raya-accent-8)",
      "chart-1": "var(--raya-accent-8)",
      "chart-2": "var(--raya-accent-10)",
      "chart-3": "var(--raya-accent-6)",
      "chart-4": "oklch(0.55 0.22 29)",
      "chart-5": "var(--raya-accent-4)",
      sidebar: "var(--raya-accent-2)",
      "sidebar-foreground": "oklch(0.2 0.01 150)",
      "sidebar-primary": "var(--raya-accent-8)",
      "sidebar-primary-foreground": "oklch(0.98 0.003 150)",
      "sidebar-accent": "var(--raya-accent-4)",
      "sidebar-accent-foreground": "oklch(0.24 0.02 150)",
      "sidebar-border": "var(--raya-accent-6)",
      "sidebar-ring": "var(--raya-accent-8)",
    }),
  },
  dark: {
    semantic: semantic({
      background: "oklch(0.16 0.012 150)",
      foreground: "var(--raya-accent-10)",
      card: "oklch(0.2 0.015 150)",
      "card-foreground": "var(--raya-accent-11)",
      popover: "oklch(0.2 0.015 150)",
      "popover-foreground": "var(--raya-accent-11)",
      primary: "var(--raya-accent-9)",
      "primary-foreground": "oklch(0.13 0.01 150)",
      secondary: "var(--raya-accent-4)",
      "secondary-foreground": "var(--raya-accent-11)",
      muted: "var(--raya-accent-3)",
      "muted-foreground": "var(--raya-accent-8)",
      accent: "var(--raya-accent-5)",
      "accent-foreground": "var(--raya-accent-12)",
      destructive: "oklch(0.6 0.21 29)",
      border: "var(--raya-accent-6)",
      input: "var(--raya-accent-6)",
      ring: "var(--raya-accent-9)",
      "chart-1": "var(--raya-accent-9)",
      "chart-2": "var(--raya-accent-11)",
      "chart-3": "var(--raya-accent-7)",
      "chart-4": "oklch(0.62 0.21 29)",
      "chart-5": "var(--raya-accent-5)",
      sidebar: "oklch(0.18 0.012 150)",
      "sidebar-foreground": "var(--raya-accent-10)",
      "sidebar-primary": "var(--raya-accent-9)",
      "sidebar-primary-foreground": "oklch(0.13 0.01 150)",
      "sidebar-accent": "var(--raya-accent-5)",
      "sidebar-accent-foreground": "var(--raya-accent-11)",
      "sidebar-border": "var(--raya-accent-6)",
      "sidebar-ring": "var(--raya-accent-9)",
    }),
  },
  knobs: {
    button: { variant: "outline", size: "sm" },
    card: { density: "compact" },
    badge: { size: "sm" },
    avatar: { shape: "square", size: "sm" },
  },
};
